# fishros deploy tool 所有的操作都在工程目录进行
name: nav2doc
tag: master
pipline:
  - delete
  - install
stages:
  delete:
    - rm -rf /root/nav2/master/doc/*
    - rm -rf /root/nav2/dev/doc/*
  install:
    - cp -r * /root/nav2/master/doc/
    - cp -r * /root/nav2/dev/doc/
